### ISSUE TITLE
No real issue, just curiosity.

### ISSUE THREAD

**Issue by jchnkl** [jaagr/xpp#5]
Hi Michael,

did you pick up the project, i.e. do you actively work on it?

Or do you even use it in a different project?

Anyway, just wanted to say that it makes me very happy that you took care of it. Thank you very much! :)

**Comment by jaagr** [comment]
Hi,

Yeah, I use it in a project http://github.com/jaagr/polybar but I haven't
made any changes to it apart from making it work with CMake.

Thank you for writing it. It has made working with xcb alot more pleasent :)
